---
  - hosts: webserver
    become_method: sudo
    remote_user: root
    tasks:      
      - name: check the status of nginx server
        nginx_status_facts:
          url: http://54.145.63.207
        register: services_state
      - name: debug
        debug:
          var: services_state
      - name: copy the output to a local file
        copy:
          content: "{% for hostoutput in services_state %}{{ hostoutput }}{% endfor %}"
          dest: "/home/ec2-user/devops-challenge/ansible/output.txt"
        delegate_to: localhost
